# Used for GitHub Actions, missing certs
services:
  nextjs-dev:
    container_name: nextjs-dev
    build:
      context: ./nextjs
      dockerfile: Dockerfile.dev
    # mount the entire Next.js application directory for HMR
    environment:
      - NODE_ENV=development 
      - WATCHPACK_POLLING=true
    volumes:
      - ./nextjs:/app 

  nginx-dev:
    container_name: nginx-dev
    image: nginx:1.26.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs-dev
