# Used for GitHub Actions
services:
  nextjs-dev:
    container_name: nextjs-dev
    build: .

  nginx-dev:
    container_name: nginx-dev
    image: nginx:1.26.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs-dev
