# Used for GitHub Actions, missing certs
services:
  # nextjs-dev:
  #   container_name: nextjs-dev
  #   build: ./nextjs

  # nginx-dev:
  #   container_name: nginx-dev
  #   image: nginx:1.26.0-alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.dev.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - nextjs-dev

  strapi:
    container_name: strapi
    build: ./strapi
    image: strapi:latest
    restart: unless-stopped
    env_file: ./strapi/.env
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/package-lock.json:/opt/package-lock.json
      # no yarn
      - ./strapi/.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
      
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./strapi/.env
    image: postgres:14.5-alpine
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - strapi
      
volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
