FROM node:23-alpine3.19

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

# Set the timezone to Finnish time
ENV TZ=Europe/Helsinki

EXPOSE 3000
ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
