FROM node:22-alpine3.19

WORKDIR /app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

# Set the timezone to Finnish time
ENV TZ=Europe/Helsinki

EXPOSE 3000
ENV NODE_ENV=development

CMD ["pnpm", "run", "dev"]
